[package]
name = "pile_of_cubes"
version = "0.1.0"
authors = ["akf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
